Repository rafsandwich/Group-Project-Advanced-Data-Week-1, pull requests merged in 2025-06, with the labels that each got.

#24 19 - Asynchronously extracting data from the API.
  .gitignore
  pipeline_live_data/extract.py
  pipeline_live_data/requirements.txt
Labels: enhancement

#61 54 - Implement logging in transform & create tests
  pipeline_live_data/test_transform.py
  pipeline_live_data/transform.py
Labels: enhancement, improvement

#78 71 - Creating json file of table data.
  .gitignore
  pipeline_live_data/transform.py
Labels: enhancement

#81 69 - Terraform Lambda and S3 bucket for the archived data pipeline.
  terraform/ECR/README.md
  terraform/ECR/ecr.tf
  terraform/pipeline_archived_data/README.md
  terraform/pipeline_archived_data/pipeline_archived.tf
  terraform/pipeline_live_data/README.md
Labels: enhancement

#93 66 - Create basis of archive pipeline
  .gitignore
  pipeline_archived_data/Dockerfile
  pipeline_archived_data/README.md
  pipeline_archived_data/extract.py
  pipeline_archived_data/load.py
  pipeline_archived_data/requirements.txt
  pipeline_archived_data/transform.py
Labels: enhancement

#103 102 - Additional linting for seed database
  pipeline_live_data/seed_database.py
  pipeline_live_data/test_transform.py
Labels: improvement

#107 20 Create live dashboard page
  dashboard/pages/live_data.py
  dashboard/pages/resources/live_data/charts.py
  dashboard/pages/resources/live_data/extract.py
  dashboard/requirements.txt
Labels: enhancement

#108 22 - Archived Data Dashboard Page
  dashboard/pages/archived_data.py
  dashboard/pages/resources/archived_data/charts.py
  dashboard/pages/resources/archived_data/extract.py
Labels: enhancement

#106 90 - Update README.md
  README.md
Labels: improvement
